
import * as ORDER_STATUS_REASONCODES from './order-status-codes.json';

export enum FASTSTART_ORDER_STATUS {

  FASTSTART_STATUS_DENIED = 'NX:Order has been Denied',
  FASTSTART_STATUS_PROCESSED_1 = 'NX:Order has been Processed',
  FASTSTART_STATUS_PROCESSED_2 = 'NX:Order Processed',
  FASTSTART_STATUS_FAX_RECEIVED = 'NX:Fax received. Ready to Process.',
  FASTSTART_STATUS_RECEIVED_PROCESSED = 'NX:Fax Received and order Processed.',
  FASTSTART_STATUS_NO_RESPONSE = 'NX:Fax not received and No Reply(Televox File Created)',
  FASTSTART_STATUS_CANCELLED = 'NX:Order has been Cancelled',
  FASTSTART_STATUS_FAX_NOT_SENT = 'NX:Ready to Process(Fax Not Sent)',
  FASTSTART_STATUS_IN_PROCESS = 'In Process',
  FASTSTART_STATUS_CANCELED = 'Canceled',
  FASTSTART_STATUS_DEFAULT = 'In Process',

}

export enum FASTSTART_ORDER_STATUS_DESCRIPTION {

  FASTSTART_STATUS_DESCRIPTION_DEFAULT = 'We are processing your new prescription request.',
  FASTSTART_STATUS_DESCRIPTION_IN_PROCESS = 'We have received a response from your prescriber related to this prescription.',
  FASTSTART_STATUS_DESCRIPTION_CANCELED = 'This prescription order cannot be filled. Please <a href=\'/wps/myportal/CONTACT_CAREMARK\'> contact Customer care</a> for more details.',
  FASTSTART_STATUS_DESCRIPTION_DENIED = 'Your prescriber denied this prescription request, so it will not be filled. Please contact your prescriber for more details.',
  FASTSTART_STATUS_DESCRIPTION_NO_RESP = 'We have not received a response from your prescriber, so this prescription request will not be filled. Please tell your prescriber to call us toll free at 1-800-378-5697 if you still need this medicine.',
}

export const FASTSTART_ORDER_STATUS_MAP = {};


FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_RECEIVED_PROCESSED] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_IN_PROCESS;
FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_PROCESSED_1] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_IN_PROCESS;
FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_FAX_RECEIVED] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_IN_PROCESS;
FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_PROCESSED_2] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_IN_PROCESS;
FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_CANCELLED] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_CANCELED;
FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_DENIED] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_CANCELED;
FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_NO_RESPONSE] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_CANCELED;
FASTSTART_ORDER_STATUS_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_FAX_NOT_SENT] = FASTSTART_ORDER_STATUS.FASTSTART_STATUS_DEFAULT;


export const FASTSTART_ORDER_STATUS_DESCRIPTION_MAP = {};

FASTSTART_ORDER_STATUS_DESCRIPTION_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_RECEIVED_PROCESSED] = FASTSTART_ORDER_STATUS_DESCRIPTION.FASTSTART_STATUS_DESCRIPTION_IN_PROCESS;
FASTSTART_ORDER_STATUS_DESCRIPTION_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_PROCESSED_1] = FASTSTART_ORDER_STATUS_DESCRIPTION.FASTSTART_STATUS_DESCRIPTION_IN_PROCESS;
FASTSTART_ORDER_STATUS_DESCRIPTION_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_FAX_RECEIVED] = FASTSTART_ORDER_STATUS_DESCRIPTION.FASTSTART_STATUS_DESCRIPTION_IN_PROCESS;
FASTSTART_ORDER_STATUS_DESCRIPTION_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_PROCESSED_2] = FASTSTART_ORDER_STATUS_DESCRIPTION.FASTSTART_STATUS_DESCRIPTION_IN_PROCESS;
FASTSTART_ORDER_STATUS_DESCRIPTION_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_CANCELLED] = FASTSTART_ORDER_STATUS_DESCRIPTION.FASTSTART_STATUS_DESCRIPTION_CANCELED;
FASTSTART_ORDER_STATUS_DESCRIPTION_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_DENIED] = FASTSTART_ORDER_STATUS_DESCRIPTION.FASTSTART_STATUS_DESCRIPTION_DENIED;
FASTSTART_ORDER_STATUS_DESCRIPTION_MAP[FASTSTART_ORDER_STATUS.FASTSTART_STATUS_NO_RESPONSE] = FASTSTART_ORDER_STATUS_DESCRIPTION.FASTSTART_STATUS_DESCRIPTION_NO_RESP;

export const ORDER_STATUS_CODES_MAP = {};

for (const entry of (<any>ORDER_STATUS_REASONCODES).StatusCodes) {
   ORDER_STATUS_CODES_MAP[entry.ReasonCode] = {ReasonCodePriority: entry.ReasonCodePriority, RxStatus: entry.RxStatus, RxStatusDescription: entry.RxStatusDescription};
}

export const ORDER_STATUS_CODES_ATTENTION_ONHOLDS = ['12'];

//  make Dr.On hold order status as priority being first element
export const ORDER_STATUS_CODES_ON_HOLD = ['12'];
for (const key in  ORDER_STATUS_CODES_MAP) {
  if (ORDER_STATUS_CODES_MAP[key].RxStatus.toUpperCase() === 'On Hold'.toUpperCase()) {
    ORDER_STATUS_CODES_ON_HOLD.push(key);
  }
}


export const enum ORDER_STATUS_TYPES {
  FAST_ORDER = 'FASTSTART',
  REFILL     = 'REFILL'
}
